### ISSUE TITLE
Next Steps

### ISSUE THREAD

**Issue by MMS-27** [OverShifted/OverEngine#3]
What is the Next Steps or the Future plans of the Engine ?

**Comment by OverShifted** [comment]
Hi.
I should document it somewhere but let me just tell it here.

1. Scripting (with Lua)
2. Physics Joints and Callbacks
3. A 2D editor which can be used to make some games with
4. Create a game and publish it as a demo + test engine and editor
5. Add Vulkan and DirectX support
6. Maybe Mac support
6. Go 3D (renderer, physics, ...)
7. 3D editor
8. 3D game as demo + test engine and editor
... (I don't have more plans!)

**Comment by MMS-27** [comment]
Hi there , I Know DirectX11 and i am working on it , I have an Renderer I am working on it . BTW C# Scripting would be better compared to Lua use Mono Framework .

**Comment by OverShifted** [comment]
Well, that is probably after Lua but I will definitely support that.

**Comment by salahchafai** [comment]
@OverShifted ik this discussion has been closed but I agree with @MMS-27, c# would be a better fit for scripting, more ppl are using it (especially in game dev), it has better performance and is more advanced

**Comment by OverShifted** [comment]
OK.
After a little bit of experimenting with embedding Lua, I discovered it is not what I wanted.
so C# will be the language.

**Comment by dylanclarke890** [comment]
I just want to point out to any interested parties that this is basically a fork of an existing engine - TheCherno/Hazel, in case you wanted to use the engine of the person that actually developed it ;)

**Comment by OverShifted** [comment]
> I just want to point out to any interested parties that this is basically a fork of an existing engine - TheCherno/Hazel, in case you wanted to use the engine of the person that actually developed it ;)

It's not a fork, but it was initially made by following Hazel's YouTube videos. So that's why they are so similar. But, for example OE got Box2D support sooner than Hazel. It also uses  [Wren](https://wren.io) instead of C#.
