### ISSUE TITLE
Exception when creating a new project

### ISSUE THREAD

**Issue by salahchafai** [OverShifted/OverEngine#5]
whenever I try to create a new project I get this exception 
![Capture](https://user-images.githubusercontent.com/64394387/105424021-cfe09480-5c46-11eb-95f7-1eab13041f17.PNG)
I'm using windows 10, I made the build using vs2019

**Comment by OverShifted** [comment]
Hi.
Right now, creating a new project; is not possible because the YAML file is not serialized correctly. you can still experiment with Sandbox and I will fix this soon 😉

**Comment by salahchafai** [comment]
good to know it'll be fixed,
tho, i don't think the thread should be closed since the issue is still there (so other ppl can know it's being worked on...)
